---
common_packages:
  - jq
  - curl
  - wget
  - unzip
  - htop
  - net-tools
  - vim

common_sysctl_params:
  vm.max_map_count: 262144
  vm.swappiness: 1
  net.core.somaxconn: 65535
  net.ipv4.tcp_max_syn_backlog: 65535

common_timezone: Asia/Ho_Chi_Minh

ntp_enabled: true

firewalld_enabled: false
