---
all:
  children:
    weaviate:
      hosts:
        weaviate-stag:
          ansible_host: "{{ lookup('env', 'WEAVIATE_HOST') | default('10.0.10.x', true) }}"
          ansible_user: ec2-user

    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"

  vars:
    env: stag
    aws_region: ap-southeast-1
    project_name: platform-rag
    name_prefix: platform-rag-stag
