---
# Encrypt this file: ansible-vault encrypt inventories/prod/group_vars/vault.yml
# Edit: ansible-vault edit inventories/prod/group_vars/vault.yml

vault_rds_master_password: "ducanhdeptrai"
vault_jwt_secret: "ducanhdeptrai"
vault_harbor_admin_password: "ducanhdeptrai"
vault_argocd_admin_password: "ducanhdeptrai"
