image:
  tag: "latest"

replicaCount: 2

env:
  DATABASE_URL: "postgresql://dbadmin:ducanhdeptrai@platform-rag-stag-auth-db.xxxxxx.ap-southeast-1.rds.amazonaws.com:5432/auth_db"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
